CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(40) ,
    PHONE VARCHAR(10),
    ADDRESS VARCHAR(100),
    TYPE_OF_CUSTOMER INT
);

CREATE TABLE SERVICES(
    SERVICE VARCHAR(10) PRIMARY KEY
);

CREATE TABLE SERVICE_COUNTER(
    SERVICE_COUNTER_ID INT PRIMARY KEY,
    SERVICE VARCHAR(10) REFERENCES SERVICES(SERVICE)
);

CREATE TABLE TOKEN(
    TOKEN_ID INT PRIMARY KEY,
    CUSTOMER_ID INT REFERENCES CUSTOMER(CUSTOMER_ID),
    TOKEN_STATUS INT ,
    PRIORITY INT ,
    SERVICE VARCHAR(10) REFERENCES SERVICES(SERVICE),
    SERVICE_COUNTER_ID INT REFERENCES SERVICE_COUNTER(SERVICE_COUNTER_ID),
    MESSAGE VARCHAR(50)
);